### PR TITLE
Adjust box width to let them fit on a row

### PR DESCRIPTION
**Pull request by atoomic**
Also use the 'card' class for the empty card
on the second row, to make sure all boxes align
with each others.

### CODE REVIEW

**Comment by rspier** [comment]
Thanks.  I'd prefer not to merge this because it makes the boxes different widths, which looks weird.  (Yes, the current situation also looks weird.)

What about reducing the margins on the sides?  Or not putting them in rows, and just letting them flow?  So wide screens would have 3 across, narrower 2 or 1?

**Comment by atoomic** [comment]
I do not know why this suddenly appears, the goal was to have two lines and 3 boxes per line.
My first attempt in this commit was to make all of them `3`, but then realize that we can make a few boxes wider, and I picked the one where we could expect wider content... this why it became `4, 3, 4`.

I understand your concern and can fix it by making all of them `3`

not sure about not putting them in rows... this could lead to unexpected layout, but maybe...

I'm going with a second attempt `3,3,3` :-)

**Comment by atoomic** [comment]
@rspier I've applied your idea via c4975f6e and at first glance it looks great on phone, tablet and regular screen resolutions :-)

**Comment by rspier** [comment]
I merged c4975f6  but didn't pull in the "width-3" change because it made the boxes too narrow.

More work needs to be done, but this is a huge improvement.

**Comment by rspier** [comment]
I just pushed another change that tweaked things a little more to make 3 across work even better, at the cost of borders.

The inside of the boxes is still a little odd.  We might be happier targeting 2 across on most screens to have more width to play with to keep things even.

**Pull request closed without merging**
